name: FOSSA Workflow

on:
  push:
    branches:
    - main

jobs:
  fossa-check:
    runs-on: ubuntu-latest
    steps:
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Add exec permission
      run: chmod +x gradlew
    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v5
    - name: Disable configuration cache
      run: echo -e "\norg.gradle.unsafe.configuration-cache=false\n" >> gradle.properties
    #- name: Generate dependencies report
    #  run: ./gradlew :app:dependencies > dependencies.txt
    - name: FOSSA Action
      uses: fossas/fossa-action@v1
      with:
        api-key: ${{ secrets.FOSSA_API_KEY }}
